services:
  - type: web
    name: hoopscout
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --config gunicorn_config.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
